// Code generated by protoc-gen-go. DO NOT EDIT.
// source: context.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Context struct {
	// Name of the service that produced this event.
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Version of the service that produced this event.
	ServiceVersion string `protobuf:"bytes,2,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	// Command that initiated this context.
	Command *any.Any `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	// Access token of the principal user.
	AccessToken string `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// ID of the principal account that sent the command.
	PrincipalId string `protobuf:"bytes,5,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	// Role of the principal account that sent the command.
	PrincipalRole        string   `protobuf:"bytes,6,opt,name=principal_role,json=principalRole,proto3" json:"principal_role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64063be2fc89884, []int{0}
}
func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Context) GetServiceVersion() string {
	if m != nil {
		return m.ServiceVersion
	}
	return ""
}

func (m *Context) GetCommand() *any.Any {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Context) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Context) GetPrincipalId() string {
	if m != nil {
		return m.PrincipalId
	}
	return ""
}

func (m *Context) GetPrincipalRole() string {
	if m != nil {
		return m.PrincipalRole
	}
	return ""
}

func init() {
	proto.RegisterType((*Context)(nil), "arcus.pkg.service.internal.pb.Context")
}

func init() { proto.RegisterFile("context.proto", fileDescriptor_b64063be2fc89884) }

var fileDescriptor_b64063be2fc89884 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xce, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x71, 0x3a, 0xe7, 0x86, 0x99, 0x9b, 0x10, 0x3c, 0x44, 0x41, 0x98, 0x82, 0xb8, 0x53,
	0x06, 0xfa, 0x17, 0xa8, 0x27, 0x2f, 0x1e, 0x8a, 0x78, 0xf0, 0x52, 0xd2, 0xf4, 0x59, 0xc2, 0xd2,
	0xf7, 0x42, 0x92, 0x0d, 0xf7, 0x6f, 0xfb, 0x17, 0x48, 0x9b, 0xb6, 0x5e, 0xbf, 0x7c, 0x92, 0xf7,
	0x63, 0x4b, 0x4d, 0x18, 0xe1, 0x27, 0x4a, 0xe7, 0x29, 0x12, 0xbf, 0x51, 0x5e, 0xef, 0x83, 0x74,
	0xbb, 0x5a, 0x06, 0xf0, 0x07, 0xa3, 0x41, 0x1a, 0x8c, 0xe0, 0x51, 0x59, 0xe9, 0xca, 0xeb, 0xab,
	0x9a, 0xa8, 0xb6, 0xb0, 0xed, 0x70, 0xb9, 0xff, 0xde, 0x2a, 0x3c, 0xa6, 0x97, 0x77, 0xbf, 0x19,
	0x9b, 0xbf, 0xa6, 0xbf, 0xf8, 0x2d, 0x3b, 0xef, 0x5f, 0x17, 0xa8, 0x1a, 0x10, 0xd9, 0x3a, 0xdb,
	0x9c, 0xe5, 0x8b, 0xbe, 0xbd, 0xab, 0x06, 0xf8, 0x03, 0xbb, 0x18, 0xc8, 0x01, 0x7c, 0x30, 0x84,
	0x62, 0xd2, 0xa9, 0x55, 0x9f, 0x3f, 0x53, 0xe5, 0x92, 0xcd, 0x35, 0x35, 0x8d, 0xc2, 0x4a, 0x9c,
	0xac, 0xb3, 0xcd, 0xe2, 0xf1, 0x52, 0xa6, 0x11, 0x72, 0x18, 0x21, 0x9f, 0xf1, 0x98, 0x0f, 0xa8,
	0xbd, 0xad, 0xb4, 0x86, 0x10, 0x8a, 0x48, 0x3b, 0x40, 0x31, 0x4d, 0xb7, 0x53, 0xfb, 0x68, 0x53,
	0x4b, 0x9c, 0x37, 0xa8, 0x8d, 0x53, 0xb6, 0x30, 0x95, 0x38, 0x4d, 0x64, 0x6c, 0x6f, 0x15, 0xbf,
	0x67, 0xab, 0x7f, 0xe2, 0xc9, 0x82, 0x98, 0x75, 0x68, 0x39, 0xd6, 0x9c, 0x2c, 0xbc, 0x4c, 0xbf,
	0x26, 0xae, 0x2c, 0x67, 0xdd, 0x92, 0xa7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0x34, 0xb7,
	0x67, 0x4c, 0x01, 0x00, 0x00,
}
